name: "blog feed ci"
on:
   workflow_dispatch:
   push:
   schedule:
      - cron: "0 15 * * *"

jobs:
   readme:
      runs-on: ubuntu-latest
      outputs:
         changed: ${{ steps.feed.outputs.changed }}
         items: ${{ steps.feed.outputs.items }}
      steps:
         - uses: actions/checkout@v2
         - uses: sarisia/actions-readme-feed@v1
           id: feed
           with:
              url: |
                 https://zenn.dev/k_kuroguro/feed
              file: "README.md"
              timezone: "Asia/Tokyo"
              ensure_all: true
         - name: push to master
           if: steps.feed.outputs.changed == true
           id: commit
           uses: sarisia/actions-commit@master
           with:
              message: "docs: update feed"
